name: labelnation
version: '218-1'
summary: command-line label-printing program
description: |
  LabelNation is a command-line program for making labels: address labels,
  business cards, or anything else involving regularly-arranged rectangles on a
  printer-ready sheet. It is for users who are comfortable dealing with text-
  and option-based configuration, as opposed to a graphical user interface.
confinement: strict
grade: stable

apps:
  labelnation:
    command: trunk/labelnation

parts:
  labelnation:
    plugin: dump
    source: http://svn.red-bean.com/repos/labelnation
    source-type: svn
    source-commit: '218'
    stage-packages:
      - python
